project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "EDUC 315: Principles of Teaching Math and Science in Urban Classrooms II (Grades 4-6)"
  description: "Course site for EDUC 315 at Howard University"
  site-url: "https://educ315-fa24.github.io"
  
  repo-url: "https://github.com/professornaite/educ315-fa24/"
  
  open-graph: true

  page-footer:
    right: "This page was built by Nathan Alexander, PhD in [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Nathan Alexander"
    background: "#D9E3E4"
   
  sidebar:
    background: "#D9E3E4"
    logo: "img/gladys-west.png"
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/professornaite/educ315-fa24/
        text: "GitHub organization"
      - icon: code-square
        href: https://canvas.howard.edu/courses/53402
        text: "Canvas site"
  
    style: "docked"
    search: true
    collapse-level: 1
    contents:  
    - section: "Course information"
      contents:
        - href: index.qmd
          text: Course landing page
        - href: course-overview.qmd
          text: Overview
        - href: assignments.qmd
          text: Assignments
        - href: schedule.qmd
          text: Schedule
    - section: "Modules"
      contents:
        - href: module01.qmd
          text: Module 1
        - href: module02.qmd
          text: Module 2
        - href: module03.qmd
          text: Module 3
        - href: module04.qmd
          text: Module 4
        - href: module05.qmd
          text: Module 5
        - href: module06.qmd
          text: Module 6
        - href: module07.qmd
          text: Module 7
        - href: module08.qmd
          text: Module 8
        - href: module09.qmd
          text: Module 9
        - href: module10.qmd
          text: Module 10
        - href: module11.qmd
          text: Module 11
        - href: module12.qmd
          text: Module 12
        - section: "Standards and Curricula"
          contents: 
            - href: standards/ngss.qmd
              text: Next Generation Science Standards (NGSS)
            - href: standards/nctm.qmd
              text: National Council of Teachers of Mathematics (NCTM)
            - href: standards/osse.qmd
              text: Office of the State Superintendent of Education (OSSE)
            - href: standards/umoja.qmd
              text: Umoja Curriculum
            - href: standards/freedom.qmd
              text: Freedom School Curriculum
        - section: "HW"
          contents:
            - href: hw/hw1.qmd
              text: HW 1
            - href: hw/hw2.qmd
              text: HW 2
            - href: hw/hw3.qmd
              text: HW 3
            - href: hw/hw4.qmd
              text: HW 4
        - href: solutions.qmd
          text: "Solutions"

format:
  html:
    theme: 
      light: [cosmo, style/data202.scss]
      dark: [cosmo, style/data202.scss, style/theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    callout-appearance: simple
    colorlinnks: true
    code-copy: true
    code-overflow: wrap
    toc: true

execute: 
  freeze: auto
    
editor: visual