---
title: "Assignments"
subtitle: "Principles of Teaching Math and Science in Urban Classrooms II (Grades 4-6)"
---

### **Overview of course assignments**

Our course assignments will be split between four assignment groups.

+-------------------------------------------+-------------------------------------------------------------------------------------------+-----------------+
| Assignment group                          | Assignment                                                                                | Due date        |
+===========================================+===========================================================================================+=================+
| **Reflections and position statements**   |                                                                                           |                 |
+-------------------------------------------+-------------------------------------------------------------------------------------------+-----------------+
|                                           | Position statement #1                                                                     | Thu Aug 29      |
+-------------------------------------------+-------------------------------------------------------------------------------------------+-----------------+
|                                           | Reflection: Mathematics autobiography                                                     | Thu Sept 5      |
+-------------------------------------------+-------------------------------------------------------------------------------------------+-----------------+
|                                           | Position statement 2                                                                      | Thu Sept 12     |
+-------------------------------------------+-------------------------------------------------------------------------------------------+-----------------+
|                                           | Position statement 3                                                                      | Thu Sept 25     |
+-------------------------------------------+-------------------------------------------------------------------------------------------+-----------------+
|                                           | Position statement 4                                                                      | Thu Oct 10      |
+-------------------------------------------+-------------------------------------------------------------------------------------------+-----------------+
| **Classroom activities and lesson plans** |                                                                                           |                 |
+-------------------------------------------+-------------------------------------------------------------------------------------------+-----------------+
|                                           |                                                                                           |                 |
+-------------------------------------------+-------------------------------------------------------------------------------------------+-----------------+
|                                           | Mathematics lesson draft                                                                  | Thu Oct 17      |
|                                           |                                                                                           |                 |
|                                           | Mathematics lesson (complete)                                                             | Thu Nov 7       |
+-------------------------------------------+-------------------------------------------------------------------------------------------+-----------------+
|                                           |                                                                                           |                 |
+-------------------------------------------+-------------------------------------------------------------------------------------------+-----------------+
|                                           | Science activity draft                                                                    | Thu Oct 31      |
|                                           |                                                                                           |                 |
|                                           | Science activity (complete)                                                               | Thu Nov 21      |
+-------------------------------------------+-------------------------------------------------------------------------------------------+-----------------+
|                                           | Academic communities map                                                                  | Thu Nov 27      |
+-------------------------------------------+-------------------------------------------------------------------------------------------+-----------------+
|                                           | Assessment plan                                                                           | Thu Dec 5       |
+-------------------------------------------+-------------------------------------------------------------------------------------------+-----------------+
| **Quizzes** (in class)                    |                                                                                           |                 |
+-------------------------------------------+-------------------------------------------------------------------------------------------+-----------------+
|                                           | Quiz 1: Basic concepts (zero and infinity)                                                | Wed Aug 28      |
+-------------------------------------------+-------------------------------------------------------------------------------------------+-----------------+
|                                           | Quiz 2: Numbers and sets (natural, whole, integers, rational, irrational, and real)       | Wed Sept 11     |
+-------------------------------------------+-------------------------------------------------------------------------------------------+-----------------+
|                                           | Quiz 3: Quantity and operations (sum, difference, product, quotient, exponent, root)      | Wed Sept 25     |
+-------------------------------------------+-------------------------------------------------------------------------------------------+-----------------+
|                                           | Quiz 4: Structure and properties (commutative, associative, distributive, identity)       | Wed Oct 9       |
+-------------------------------------------+-------------------------------------------------------------------------------------------+-----------------+
|                                           | Quiz 5: Space and geometry (objects, shape, representations)                              | Mon Oct 21      |
+-------------------------------------------+-------------------------------------------------------------------------------------------+-----------------+
|                                           | Quiz 6: Change and rates (patterns and sequences, functions)                              | Wed Nov 6       |
+-------------------------------------------+-------------------------------------------------------------------------------------------+-----------------+
|                                           | Quiz 7: The scientific method (steps, hypothesis, data collection, analysis, conclusions) | Wed Nov 20      |
+-------------------------------------------+-------------------------------------------------------------------------------------------+-----------------+
| **Field placement log and excursions**    |                                                                                           |                 |
+-------------------------------------------+-------------------------------------------------------------------------------------------+-----------------+
|                                           | Excursion 1: National Portrait Gallery                                                    | Due: Fri Nov 15 |
+-------------------------------------------+-------------------------------------------------------------------------------------------+-----------------+
|                                           | Excursion 2: National Museum of African American History and Culture                      | Due: Fri Nov 29 |
+-------------------------------------------+-------------------------------------------------------------------------------------------+-----------------+
|                                           | Field placement log                                                                       | Due: Mon Dec 9  |
+-------------------------------------------+-------------------------------------------------------------------------------------------+-----------------+
